### ISSUE TITLE
激活wifi要选择内核4.187

### ISSUE THREAD

**Issue by liuhejun2020** [tuanqing/mknop#21]
激活wifi要选择内核4.187，其他两个内核无法激活wifi,希望说明一下。前两天问了这个问题结果问题关闭了。我这后来又试才试出来了！

**Comment by tuanqing** [comment]
> 激活wifi要选择内核4.187，其他两个内核无法激活wifi,希望说明一下。前两天问了这个问题结果问题关闭了。我这后来又试才试出来了！

下载action那边自动构建的再测试下
