### ISSUE TITLE
请问这个脚本会自动向镜像加入写入EMMC脚本吗？我试了下写入EMMC的命令发现并不能行

### ISSUE THREAD

**Issue by yubanmeiqin9048** [tuanqing/mknop#22]

**Comment by hcym** [comment]
写入比较麻烦，依赖多，我最后还是用的xq7的armbian老办法写入的，还是U盘吧，稳妥方便

**Comment by yubanmeiqin9048** [comment]
> 写入比较麻烦，依赖多，我最后还是用的xq7的armbian老办法写入的，还是U盘吧，稳妥方便

U盘我目前是使用一块金士顿的，但是使用过程中非常的烫（烫手），我怕用久了挂掉

**Comment by hcym** [comment]
usb3吧，我用过是烫手，u2没什么问题，特地买了一堆杂牌，物美价廉

**Comment by yubanmeiqin9048** [comment]
> usb3吧，我用过是烫手，u2没什么问题，特地买了一堆杂牌，物美价廉

USB2的，很早之前买的

**Comment by tuanqing** [comment]
> > 写入比较麻烦，依赖多，我最后还是用的xq7的armbian老办法写入的，还是U盘吧，稳妥方便
> 
> U盘我目前是使用一块金士顿的，但是使用过程中非常的烫（烫手），我怕用久了挂掉

请说明具体情况，并提供截图

**Comment by hcym** [comment]
新版完全没有问题啦
