### ISSUE TITLE
不同源码有的可以成功，有的不行。

### ISSUE THREAD

**Issue by qq892767935** [tuanqing/mknop#31]
用Lean的源码编译的固件可以完美写入emmc，但用Lienol的源码编译的固件就不行，不知何故？ 好像提示分区失败。

**Comment by tuanqing** [comment]
> 用Lean的源码编译的固件可以完美写入emmc，但用Lienol的源码编译的固件就不行，不知何故？ 好像提示分区失败。

parted这个包加了吗？

**Comment by qq892767935** [comment]
.config - OpenWrt Configuration
 > Utilities > Disc ─────────────────────────────────────────────────────────────────────────────────────────────
  ┌────────────────────────────────────────────────── Disc ───────────────────────────────────────────────────┐
  │  Arrow keys navigate the menu.  <Enter> selects submenus ---> (or empty submenus ----).  Highlighted      │  
  │  letters are hotkeys.  Pressing <Y> includes, <N> excludes, <M> modularizes features.  Press <Esc><Esc>   │  
  │  to exit, <?> for Help, </> for Search.  Legend: [*] built-in  [ ] excluded  <M> module  < > module       │  
  │  capable                                                                                                  │  
  │ ┌───────────────────────────────────────────────────────────────────────────────────────────────────────┐ │  
  │ │                < > blkdiscard................................... discard sectors on a device          │ │  
  │ │                -*- blkid........................... locate and print block device attributes          │ │  
  │ │                < > blockdev.................. call block device ioctls from the command line          │ │  
  │ │                < > cfdisk........................ display or manipulate disk partition table          │ │  
  │ │                < > cgdisk........... GPT aware disk manipulation utility for interactive use          │ │  
  │ │                < > eject.............................................. eject removable media          │ │  
  │ │                <*> fdisk.................................... manipulate disk partition table          │ │  
  │ │                < > findfs................................ find a filesystem by label or UUID          │ │  
  │ │                < > fio.................................... I/O testing and benchmarking tool          │ │  
  │ │                < > fixparts....................... A utility to fix corrupted MBR partitions          │ │  
  │ │                < > gdisk............ GPT aware disk manipulation utility for interactive use          │ │  
  │ │                < > hd-idle..................... Another idle-daemon for attached hard drives          │ │  
  │ │                < > hdparm........................... Hard disk drive configuration utilitity          │ │  
  │ │                -*- lsblk................................................. list block devices          │ │  
  │ │                < > lvm2.................................... The Linux Logical Volume Manager          │ │  
  │ │                < > mdadm.......................... A tool for managing Soft RAID under Linux          │ │  
  │ │                -*- parted........................................... parted Partition editor          │ │  
  │ │                <*> partx-utils                                                                        │ │  
  │ │                < > sfdisk............................. partition table manipulator for Linux          │ │  
  │ │                < > sgdisk............. GPT aware disk manipulation utility for scripting use          │ │  
  │ │                < > wipefs.................................... wipe a signature from a device          │ │  
  │ │                                                                                                       │ │  
  │ │

**Comment by tuanqing** [comment]
安装日志贴一下

**Comment by qq892767935** [comment]
-----------------------------------------------------
root@OpenWrt:~# n1-install
 emmc: /dev/mmcblk1
 usb:  /dev/sda
 mount bootfs...
 copy bootable file...
mount: mounting /dev/sda1 on /boot failed: Invalid argument
cp: can't stat '/boot/*': No such file or directory
 edit uEnv.txt...
sed: /install/boot/uEnv.txt: No such file or directory
mv: can't rename '/install/boot/boot-emmc.scr': No such file or directory
 umount bootfs...
 mount rootfs...
 copy rootfs...
  --> copy bin...
  --> copy etc...
  --> copy lib...
  --> copy root...
  --> copy sbin...
  --> copy usr...
  --> copy www...
  --> link lib64...
  --> link var...
 edit fstab...
 sync...
 umount rootfs...
 copy openwrt os to emmc done!
root@OpenWrt:~#

**Comment by qq892767935** [comment]
root@OpenWrt:~# n1-install
 emmc: /dev/mmcblk1
 usb:  /dev/sda
 mount bootfs...
 copy bootable file...
mount: mounting /dev/sda1 on /boot failed: Invalid argument
cp: can't stat '/boot/*': No such file or directory
 edit uEnv.txt...
sed: /install/boot/uEnv.txt: No such file or directory
mv: can't rename '/install/boot/boot-emmc.scr': No such file or directory
 umount bootfs...
 mount rootfs...
 copy rootfs...
  --> copy bin...
  --> copy etc...
  --> copy lib...
  --> copy root...
  --> copy sbin...
  --> copy usr...
  --> copy www...
  --> link lib64...
  --> link var...
 edit fstab...
 sync...
 umount rootfs...
 copy openwrt os to emmc done!
root@OpenWrt:~#

**Comment by tuanqing** [comment]
同步最新的install-program试下

**Comment by qq892767935** [comment]
每次编译都是下载最新源码，Lionel旧源码op19文件夹全删除，从头开始。难道是Lionel源码和lean的文件系统不一样？第一句错误是语法错误，但在lean的源码编译的固件却可以成功生成固件，并成功刷入emmc。Lionel源码也可以生成固件并成功用u盘启动openwrt,但写入emmc却提示错误。

**Comment by tuanqing** [comment]
> 每次编译都是下载最新源码，Lionel旧源码op19文件夹全删除，从头开始。难道是Lionel源码和lean的文件系统不一样？第一句错误是语法错误，但在lean的源码编译的固件却可以成功生成固件，并成功刷入emmc。Lionel源码也可以生成固件并成功用u盘启动openwrt,但写入emmc却提示错误。

今天修正了，理论上没问题了，你可以试下。有问题再带截图反馈

**Comment by qq892767935** [comment]
![QQ截图20200709210449](https://user-images.githubusercontent.com/29705885/87043856-4d533300-c228-11ea-865e-ab17202dc642.png)

**Comment by qq892767935** [comment]
![截图录屏_选择区域_20200709211243](https://user-images.githubusercontent.com/29705885/87044615-601a3780-c229-11ea-8482-c84897283bb6.png)
![截图录屏_选择区域_20200709211318](https://user-images.githubusercontent.com/29705885/87044625-63adbe80-c229-11ea-83a1-6b20d6ec98ef.png)
![截图录屏_选择区域_20200709211347](https://user-images.githubusercontent.com/29705885/87044632-65778200-c229-11ea-9266-fcf3282d77c1.png)
![Uploading 截图录屏_dde-file-manager_20200709211412.png…](
![截图录屏_选择区域_20200709211513](https://user-images.githubusercontent.com/29705885/87044639-68727280-c229-11ea-8a6b-4b43fe6e468f.png)

大神帮忙看看   个人比较喜欢用lionel的源码。

**Comment by qq892767935** [comment]
Lienol
打错字了

**Comment by tuanqing** [comment]
同步下install-program

**Comment by qq892767935** [comment]
![QQ截图20200710075242](https://user-images.githubusercontent.com/29705885/87101725-6f799f00-c282-11ea-95f7-2718bdb07815.png)
问题依旧呢0.0

**Comment by tuanqing** [comment]
现在呢

**Comment by qq892767935** [comment]
![截屏图片](https://user-images.githubusercontent.com/29705885/87130760-fa2fbd80-c2c5-11ea-843b-d2309029111b.jpg)
重新拉去你的一键脚本源码，还是一样呢。

**Comment by qq892767935** [comment]
![截屏图片](https://user-images.githubusercontent.com/29705885/87130881-2e0ae300-c2c6-11ea-87cb-000bd3c555fe.jpg)
重新拉取你的一键源码制作，还是一样呢。

**Comment by qq892767935** [comment]
重新拉取你的一键源码制作，还是一样呢。
![截屏图片](https://user-images.githubusercontent.com/29705885/87131017-5f83ae80-c2c6-11ea-9716-04ef91919172.jpg)

**Comment by tuanqing** [comment]
把你的固件传过来看看

**Comment by tuanqing** [comment]
把你的固件发过来看一下，谢谢

qq892767935 <notifications@github.com> 于2020年7月10日周五 下午4:00写道：

**Comment by qq892767935** [comment]
https://yangmantang.lanzous.com/iZFxuehijha

https://cloud.189.cn/t/iMraIneieyI3

**Comment by qq892767935** [comment]
限制10M没法上传，只能放网盘了 。麻烦大神了。

**Comment by tuanqing** [comment]
> 限制10M没法上传，只能放网盘了 。麻烦大神了。

https://cloud.189.cn/t/yiMV3aVj6Bv2
可以了

**Comment by qq892767935** [comment]
先谢谢大神，等下吃完饭试下，顺便问下，大神问题何故？

**Comment by tuanqing** [comment]
> 先谢谢大神，等下吃完饭试下，顺便问下，大神问题何故？

我的锅，判断条件不严谨

**Comment by qq892767935** [comment]
谢谢大佬

**Comment by tuanqing** [comment]
> 谢谢大佬

应该🆗了吧？下次使用最新的install-program就行了
