### ISSUE TITLE
最新编译的好像用不了

### ISSUE THREAD

**Issue by coaens** [tuanqing/mknop#35]
5.4 和 4.19 都试了，U盘安上启动后网口没有反应

**Comment by hcym** [comment]
也是，硬加入网络设置可以启动，还是不稳基本上不能用，不知道怎么回事。

**Comment by qq892767935** [comment]
确实  现在生成的固件无法启动

**Comment by tuanqing** [comment]
你好，经测试，该问题在新版得到已解决，请同步最新 mknop 和 install-program 再构建测试一下是否正常 @coaens @hcym @qq892767935

**Comment by qq892767935** [comment]
谢谢  试下去

**Comment by hcym** [comment]
谢谢啦，自己编译的打包没什么问题，就是大佬自动构建的固件有问题，晚上回去试试看看

**Comment by tuanqing** [comment]
> 谢谢啦，自己编译的打包没什么问题，就是大佬自动构建的固件有问题，晚上回去试试看看

昨天晚上的一版应该没问题了，我目前再用

**Comment by hcym** [comment]
完全ok啦，感谢，😂

**Comment by coaens** [comment]
已经OK了，谢谢大佬，升级功能好评
