### ISSUE TITLE
 [ Error ] mount /dev/loop8p2 failed!

### ISSUE THREAD

**Issue by yehoshualee** [tuanqing/mknop#37]
Unbuntu 18.04版本系统,有下面的错误提示:
bdder@ubuntu:~/openwrt/mknop$ sudo ./make 
[sudo] bdder 的密码： 
 Welcome to phicomm-n1 openwrt image tools!

 firmware: 
 (1) openwrt-armvirt-64-rootfs-ext4.img
 [ openwrt-armvirt-64-rootfs-ext4.img ]

 kernel: 
 (1) 4.19.134
 (2) 5.4.50

 select kernel above, and press Enter to select the first one: 2
 [ 5.4.50 ]

 input the rootfs partition size, defaults to 512m, do not less than 256m
 if you don't know what this means, press Enter to keep default: 
 [ 512 ]

 [ 5.4.50 ] extract openwrt files 
mount: /home/bdder/openwrt/mknop/tmp/mount: 特殊设备 /dev/loop8p2 不存在.
 [ Error ] mount /dev/loop8p2 failed!

**Comment by hcym** [comment]
别用ext4的，不知道从那个版本开始不行了，以前两种格式的都可以

**Comment by necoic** [comment]
我18.04没问题

hcym <notifications@github.com> 于 2020年8月10日周一 下午9:14写道：

**Comment by hcym** [comment]
哦，这样啊，呵呵😄，无所谓啦

**Comment by hcym** [comment]
舔什么乱，楼主是1804，我是都换2004了，等大佬看看吧🤣

**Comment by yehoshualee** [comment]
> 舔什么乱，楼主是1804，我是都换2004了，等大佬看看吧🤣

我用2004也不行,如果你们没有类似问题也可能是我自己没搞好

**Comment by yehoshualee** [comment]
换成其他格式的好了
