### ISSUE TITLE
请教一下关于内核的问题

### ISSUE THREAD

**Issue by trombonist852** [tuanqing/mknop#38]
大神，麻问一下，我用li大大的5.4.52的内核编译的N1的openwrt-armvirt-64-default-rootfs.tar.gz这个固件，然后我看咱们这个选项里面内核只有5.4.50，这样的话生成的固件会有影响不？？？谢谢啦！！

**Comment by hcym** [comment]
没有影响，5就选5.xxx，4就选4.xxx，其实我跨版本也打过包，没有什么感觉

**Comment by tuanqing** [comment]
> 大神，麻问一下，我用li大大的5.4.52的内核编译的N1的openwrt-armvirt-64-default-rootfs.tar.gz这个固件，然后我看咱们这个选项里面内核只有5.4.50，这样的话生成的固件会有影响不？？？谢谢啦！！

不影响，因为你用的不是op的内核

**Comment by trombonist852** [comment]
> > 大神，麻问一下，我用li大大的5.4.52的内核编译的N1的openwrt-armvirt-64-default-rootfs.tar.gz这个固件，然后我看咱们这个选项里面内核只有5.4.50，这样的话生成的固件会有影响不？？？谢谢啦！！
> 
> 不影响，因为用的不是op的内核



> 没有影响，5就选5.xxx，4就选4.xxx，其实我跨版本也打过包，没有什么感觉

好的好的  感谢！！！！
