### ISSUE TITLE
希望更新一下内核

### ISSUE THREAD

**Issue by leochien0102** [tuanqing/mknop#39]
最新的40+据说可以开启SFE加速了

**Comment by hcym** [comment]
mtk吧，arm和这些东西没什么关系，

**Comment by tuanqing** [comment]
> 最新的40+据说可以开启SFE加速了

4.19 就支持

**Comment by leochien0102** [comment]
> > 最新的40+据说可以开启SFE加速了
> 
> 4.19 就支持

哦，我用的是5.4.50的，现在勾选了SFE加速但显示是未运行，回头换4.19的看看
