### ISSUE TITLE
不知道什么原因导致挂载img的boot分区失败，加上 -a 就好了。

### ISSUE THREAD

**Issue by ikarr** [tuanqing/mknop#4]
sudo mount -a -o rw ${loop}p1 $boot_dir

https://github.com/tuanqing/mknop/blob/45202abd9d40e535ba4d3bc89fcf4419bcb1c4ba/mk.sh#L92

**Comment by ikarr** [comment]
还是不对。虽然镜像是制作好了，但是写入U盘 启动不了。我挂载img镜像后发现boot里面是空的没有文件。

**Comment by ikarr** [comment]
换成本地电脑安装的ubuntu就好了。难道是服务器上面系统内核不支持？

**Comment by tuanqing** [comment]
请尝试去掉 "-o rw" 参数

ikarr <notifications@github.com> 于2019年8月23日周五 上午9:12写道：
