### ISSUE TITLE
老大！！ 添加自定义内核 这能不能出个详细教程 我去f大那里有看到内核包，不太明白怎样整合进去

### ISSUE THREAD

**Issue by dzhuqi** [tuanqing/mknop#40]
老大！！ 添加自定义内核 这能不能出个详细教程 我去f大那里有看到内核包，不太明白怎样整合进去

**Comment by tuanqing** [comment]
> 老大！！ 添加自定义内核 这能不能出个详细教程 我去f大那里有看到内核包，不太明白怎样整合进去

你好，使用 `./make -e` 即可提取，具体参见 README
