### ISSUE TITLE
写入U盘后启动失败

### ISSUE THREAD

**Issue by bin20088** [tuanqing/mknop#41]
编译完op后用这个源码制作出img镜像，写入U盘后启动失败，如图。另外我想问一下，如果是电视盒子状态，还需要把armbian底包刷入emmc吗？
![photo_2020-08-29_21-18-00](https://user-images.githubusercontent.com/53508344/91638005-f5be9000-ea3e-11ea-877f-13ff069d9f9c.jpg)

**Comment by hcym** [comment]
U盘启动使用都正常了再写emmc，其实无所谓的，最近各种app都要变动，写来写去的麻烦，我基本上都是用U盘系统

**Comment by bin20088** [comment]
经过反复测试，同样源码同样的编译环境，固件里集成插件少的一切正常，多的就这个结果。编译用的这个架构。CONFIG_TARGET_bcm27xx=y
CONFIG_TARGET_bcm27xx_bcm2710=y
CONFIG_TARGET_bcm27xx_bcm2710_DEVICE_rpi-3=y
![photo_2020-08-30_05-48-22](https://user-images.githubusercontent.com/53508344/91646695-84a1cb80-ea84-11ea-862e-288f916e7284.jpg)

**Comment by Margular** [comment]
同样，启动失败，卡在N1盒子启动的第一个界面就不动了我是，然后拔掉U盘再重启就正常进入原系统了

**Comment by hcym** [comment]
可能有个体差异，我的n1杂食动物，老的512m和1G的U盘也能用，就是编译打包时注意到选择最小就可以，大佬的最小可以400M，运行完美😹

**Comment by goer99** [comment]
也遇到过与楼主类似的USB启动失败情况，必然发生kernel panic，百思不得其解。

写盘时使用的是一直在使用的USBWriter（只有176K），后来尝试把写盘软件换成作者所推荐的 Etcher （100多M），就启动正常了。奇怪的是，flippy编译的N1固件，使用USBWriter写盘就没问题。

不知道楼主写盘时是否用的 Etcher，如果不是，可以换成 Etcher试试。


> 编译完op后用这个源码制作出img镜像，写入U盘后启动失败，如图。另外我想问一下，如果是电视盒子状态，还需要把armbian底包刷入emmc吗？
> ![photo_2020-08-29_21-18-00](https://user-images.githubusercontent.com/53508344/91638005-f5be9000-ea3e-11ea-877f-13ff069d9f9c.jpg)

**Comment by bin000000** [comment]
确实是你说的这样，搞定了。谢谢

> 也遇到过与楼主类似的USB启动失败情况，必然发生kernel panic，百思不得其解。
> 
> 写盘时使用的是一直在使用的USBWriter（只有176K），后来尝试把写盘软件换成作者 tuanqing 所推荐的 Etcher （100多M），就启动正常了。奇怪的是，flippy编译的N1固件，使用USBWriter写盘就没问题。
> 
> 不知道楼主写盘时是否用的 Etcher，如果不是，可以换成 Etcher试试。
> 
> > 编译完op后用这个源码制作出img镜像，写入U盘后启动失败，如图。另外我想问一下，如果是电视盒子状态，还需要把armbian底包刷入emmc吗？
> > ![photo_2020-08-29_21-18-00](https://user-images.githubusercontent.com/53508344/91638005-f5be9000-ea3e-11ea-877f-13ff069d9f9c.jpg)
