### ISSUE TITLE
请问下，使用n1-install写入EMMC后，如果要恢复分区，如何操作？

### ISSUE THREAD

**Issue by ylqjgm** [tuanqing/mknop#46]
F大的写入分区是inst-to-emmc.sh，然后可以使用dd if=/root/u-boot-2015-phicomm-n1.bin  of=/dev/mmcblk1来恢复，请问下n1-install写入的要如何恢复？

主要是因为之前重新写入过，却发现自己之前安装的docker都还存在，证明没有被格式化过

**Comment by tuanqing** [comment]
你好，执行 `tune2fs -L "D" /dev/mmcblk1p3` 之后再重新写入一次就可以了，或者手动删除 /opt 中的文件

**Comment by ylqjgm** [comment]
> 你好，执行 `tune2fs -L "D" /dev/mmcblk1p3` 之后再重新写入一次就可以了，或者手动删除 `/opt` 中的文件

好的，非常感谢
