### ISSUE TITLE
大佬能安排微加云的打包不

### ISSUE THREAD

**Issue by bin20088** [tuanqing/mknop#48]
新启之秀，秒杀n1

**Comment by hcym** [comment]
不写emmc的话都可以用的，我的章鱼和s922等正常使用，无线和蓝牙可能要自己编译再用这个项目打包

**Comment by bin20088** [comment]
> 不写emmc的话都可以用的，我的章鱼和s922等正常使用，无线和蓝牙可能要自己编译再用这个项目打包

无线蓝牙可以不要，玩op这俩再怎么弄也是残疾。这个包制作的镜像真是方便，刷机升级简单暴力通俗易懂，哈哈。一直在用。还是希望能刷入emmc，因为我还外接移动硬盘，usb供电的，怕供电不足什么的

**Comment by goer99** [comment]
flippy对微加云的看法：https://www.right.com.cn/forum/thread-4049923-1-1.html

很客观。

**Comment by tuanqing** [comment]
> 新启之秀，秒杀n1

你好，vplus能正常启动嘛？

**Comment by bin20088** [comment]
大佬辛苦
