### ISSUE TITLE
ipv6

### ISSUE THREAD

**Issue by hcym** [tuanqing/mknop#5]
请教大佬，除了ipv6不通，其他都完美，是不是要添加什么内核模块？因为同一个op和其他armbian组合都有ipv6，但是负载和反应速度不太好。

**Comment by tuanqing** [comment]
4.18的armbian内核貌似不支持ipv6，你可以选择自己编译，或者使用flippy编译的新内核

**Comment by hcym** [comment]
好的，试试看看，谢谢啦
