### ISSUE TITLE
请问，这个如何启动N1的WIFI？

### ISSUE THREAD

**Issue by frankeson** [tuanqing/mknop#50]
N1的WIFI 好像开启不了。

**Comment by hcym** [comment]
默认是开了，我刚刚刷的也是这样

**Comment by frankeson** [comment]
我编译好后，没有打开，找不到无线 的选项

**Comment by tuanqing** [comment]
> 我编译好后，没有打开，找不到无线 的选项

编译时选中 `brcmfmac-firmware-43430-sdio brcmfmac-firmware-43455-sdio kmod-brcmfmac wpad` 这几个包就会有 WIFI

**Comment by frankeson** [comment]
谢谢
