### ISSUE TITLE
之前tput报错，这会又这一大堆错误，还是有点问题啊 

### ISSUE THREAD

**Issue by bin20088** [tuanqing/mknop#51]
![QQ截图20201004005728](https://user-images.githubusercontent.com/53508344/94997334-fcf83100-05dc-11eb-9dc3-c95cee2249c7.png)

**Comment by tuanqing** [comment]
谢谢反馈，该问题已修复。
另：不需要使用这么多参数，`-d` 就够了

**Comment by bin20088** [comment]
打包已成功。辛苦。另外最近又很火爆的hk1-x3，和x96-x3会考虑吗？都是S905X3四核的

**Comment by bin20088** [comment]
> 谢谢反馈，该问题已修复。
> 另：不需要使用这么多参数，`-d` 就够了

有个疑问咨询下，vplus固件也能用你的install-program命令升级写入emmc吗？
