### ISSUE TITLE
x96打包后无法开机

### ISSUE THREAD

**Issue by bin20088** [tuanqing/mknop#54]
x96max+。打包后s905x3镜像写入U盘启动成功，install命令写入EMMC后，不能开机，再把U盘插回来从U盘启动一次后，再从emmc开机就可以，但是开机后网卡只能用100M。

**Comment by bin20088** [comment]
大哥有QQ群或者TG群吗

**Comment by tuanqing** [comment]
> 大哥有QQ群或者TG群吗

有事嘛？

**Comment by bin20088** [comment]
咨询一下我提的这个问题，是我操作不当还是什么原因

**Comment by bin20088** [comment]
> > 大哥有QQ群或者TG群吗
> 
> 有事嘛？

咨询一下我提的这个问题，是我操作不当还是什么原因

**Comment by tuanqing** [comment]
> > > 大哥有QQ群或者TG群吗
> > 
> > 
> > 有事嘛？
> 
> 咨询一下我提的这个问题，是我操作不当还是什么原因

[点击链接加入群聊](https://jq.qq.com/?_wv=1027&k=aAy6dLKq)
