### ISSUE TITLE
n1-update失败

### ISSUE THREAD

**Issue by lexin8** [tuanqing/mknop#56]
执行 n1-install 安装到 emmc，将固件上传到 /tmp/upgrade( xxx.img )，之后执行 n1-update

root@OpenWrt:~# n1-update
Error: you have never installed a OS to emmc, please boot with usb and run n1-install to install at first!

**Comment by tuanqing** [comment]
> 执行 n1-install 安装到 emmc，将固件上传到 /tmp/upgrade( xxx.img )，之后执行 n1-update
> 
> root@OpenWrt:~# n1-update
> Error: you have never installed a OS to emmc, please boot with usb and run n1-install to install at first!

执行 `lsblk ` 看下

**Comment by lexin8** [comment]
> > 执行 n1-install 安装到 emmc，将固件上传到 /tmp/upgrade( xxx.img )，之后执行 n1-update
> > root@OpenWrt:~# n1-update
> > Error: you have never installed a OS to emmc, please boot with usb and run n1-install to install at first!
> 
> 执行 `lsblk ` 看下

![1](https://user-images.githubusercontent.com/61616502/96574118-a17ab280-1301-11eb-9a44-5dba6923e5d9.jpg)

**Comment by tuanqing** [comment]
> > > 执行 n1-install 安装到 emmc，将固件上传到 /tmp/upgrade( xxx.img )，之后执行 n1-update
> > > root@OpenWrt:~# n1-update
> > > Error: you have never installed a OS to emmc, please boot with usb and run n1-install to install at first!
> > 
> > 
> > 执行 `lsblk ` 看下
> 
> ![1](https://user-images.githubusercontent.com/61616502/96574118-a17ab280-1301-11eb-9a44-5dba6923e5d9.jpg)

先 `losetup -d /dev/loop0` ，然后再 `n1-update` 试试。
还不行的话就 `blkid` 然后贴张图过来看看

**Comment by lexin8** [comment]
> > > > 执行 n1-install 安装到 emmc，将固件上传到 /tmp/upgrade( xxx.img )，之后执行 n1-update
> > > > root@OpenWrt:~# n1-update
> > > > Error: you have never installed a OS to emmc, please boot with usb and run n1-install to install at first!
> > > 
> > > 
> > > 执行 `lsblk ` 看下
> > 
> > 
> > ![1](https://user-images.githubusercontent.com/61616502/96574118-a17ab280-1301-11eb-9a44-5dba6923e5d9.jpg)
> 
> 先 `losetup -d /dev/loop0` ，然后再 `n1-update` 试试。
> 还不行的话就 `blkid` 然后贴张图过来看看

![1](https://user-images.githubusercontent.com/61616502/96715079-ac067c00-13d5-11eb-810b-5a0c7584f2a6.jpg)

**Comment by tuanqing** [comment]
你好，请更新下 `install-program` ，应该是没问题了

**Comment by lexin8** [comment]
> 你好，请更新下 `install-program` ，应该是没问题了

重新编译新固件吗
