### ISSUE TITLE
云编译时空间不够？怎么办

### ISSUE THREAD

**Issue by shenzt68** [tuanqing/mknop#58]
云编译时，因为增加了一些常用插件，就出现错误了，部分日志如下。因为增加了一些常用插件，什么原因?请问如何解决？急盼大神指点！
Run cp lede/bin/targets/*/*/*.tar.gz ./openwrt
Welcome to aarch64 openwrt firmware generator!

device		=>  beikeyun, l1pro, phicomm-n1, s905x3, vplus
firmware	=>  openwrt-armvirt-64-default-rootfs.tar.gz
kernel		=>  5.4.72
rootsize	=>  512

unpack openwrt
unpack armbian  =>  beikeyun @ 5.4.72
unpack armbian  =>  s905x3 @ 5.4.72
unpack armbian  =>  vplus @ 5.4.72
unpack armbian  =>  phicomm-n1 @ 5.4.72
unpack armbian  =>  l1pro @ 5.4.72
make firmware	=>  vplus @ 5.4.72
make firmware	=>  phicomm-n1 @ 5.4.72
make firmware	=>  beikeyun @ 5.4.72
make firmware	=>  l1pro @ 5.4.72
make firmware	=>  s905x3 @ 5.4.72
cp: error writing './tmp/mount/loop1p2/usr/lib/python3.8/lib-dynload/_ssl.cpython-38.so': No space left on device
cp: error writing './tmp/mount/loop1p2/usr/lib/python3.8/lib-dynload/_statistics.cpython-38.so': No space left on device
cp: error writing './tmp/mount/loop1p2/usr/lib/python3.8/lib-dynload/_struct.cpython-38.so': No space left on device
cp: error writing './tmp/mount/loop1p2/usr/lib/python3.8/lib-dynload/_xxsubinterpreters.cpython-38.so': No space left on device
....
cp: cannot create directory './tmp/mount/loop2p2/usr/lib/rpcd': No space left on device
cp: cannot create directory './tmp/mount/loop2p2/usr/lib/samba': No space left on device
cp: cannot create directory './tmp/mount/loop2p2/usr/lib/sqm': No space left on device
cp: cannot create directory './tmp/mount/loop2p2/usr/lib/tc': No space left on device
cp: cannot create directory './tmp/mount/loop2p2/usr/libexec': No space left on device
cp: cannot create directory './tmp/mount/loop2p2/usr/man': No space left on device
cp: cannot create directory './tmp/mount/loop2p2/usr/sbin': No space left on device
cp: cannot create directory './tmp/mount/loop2p2/usr/share': No space left on device
cp: cannot create directory './tmp/mount/loop2p2/www': No space left on device

**Comment by tuanqing** [comment]
使用 `-s` 参数增大 `rootfs` 分区大小，如：`sudo ./gen_openwrt -d -k latest -s 1024`
