### ISSUE TITLE
章鱼星球

### ISSUE THREAD

**Issue by hcym** [tuanqing/mknop#59]
大佬，加了那么多，再加上s912的章鱼星球吧😂

**Comment by tuanqing** [comment]
> 大佬，加了那么多，再加上s912的章鱼星球吧😂

直接用 `N1` 的改下 `uEnv.txt` 里的 `FDT`

**Comment by hcym** [comment]
这是一直都用的，主要是bootloader不会搞，搞砖了一个🤣
