### ISSUE TITLE
脚本更新49+o内核后从打包N1固件从U盘启动始终Kernel panic

### ISSUE THREAD

**Issue by hfharry** [tuanqing/mknop#67]
脚本更新49+o内核后打包N1固件，始终出现kernel panic无法从U盘启动。将Flippy自行打包的固件拆包出rootfs后，用本脚本重新打包，仍然kernel panic。

**Comment by hcym** [comment]
没必要吧，换内核区别不大，我还用着老的66，因为哪个版本可以打包256m的，可以用512M的老老U盘，启动还快一点

**Comment by hfharry** [comment]
> 没必要吧，换内核区别不大，我还用着老的66，因为哪个版本可以打包256m的，可以用512M的老老U盘，启动还快一点

没法回滚到之前的版本了，并且把之前打包的镜像都删了……而且换了47、45内核，一样kernel panic……换台机编译Lean的源码再打包还是一样……有点魔怔了

**Comment by hcym** [comment]
默认的也正常啊，应该是f大最新的内核吧，我没搞过置换内核，因为试过以前419的老固件居然比现在的都好用，速度快，就是协议老的有点担心，崩溃😂

**Comment by hcym** [comment]
哦，lean的源码最近两个月都有问题，就是gfwset.sh启动占用cpu非常高，x86的都非常明显，我都是用的官方源码或者pass及其它的翻墙插件编译打包，但是看看没什么人反应这个问题，活见鬼

**Comment by tuanqing** [comment]
> 脚本更新49+o内核后打包N1固件，始终出现kernel panic无法从U盘启动。将Flippy自行打包的固件拆包出rootfs后，用本脚本重新打包，仍然kernel panic。

可以试一下自动编译的版本，本人目前贝壳云使用没问题
