### ISSUE TITLE
N1脚本更新49+o内核后，无线丢失。

### ISSUE THREAD

**Issue by i5g5vip** [tuanqing/mknop#68]
还好有两个虚拟机有48+o备份。
换回48+o无线正常。

开始以为是lede更新后问题，切老版本编译一次，还是不行。
换老内核好了

此仓库不支持版本回退。回退后内核文件不见了。还好备份有。

**Comment by tuanqing** [comment]
> 还好有两个虚拟机有48+o备份。
> 换回48+o无线正常。
> 
> 开始以为是lede更新后问题，切老版本编译一次，还是不行。
> 换老内核好了
> 
> 此仓库不支持版本回退。回退后内核文件不见了。还好备份有。

等下个版本看看，有需要就先用旧版吧

**Comment by hfharry** [comment]
> > 还好有两个虚拟机有48+o备份。
> > 换回48+o无线正常。
> > 开始以为是lede更新后问题，切老版本编译一次，还是不行。
> > 换老内核好了
> > 此仓库不支持版本回退。回退后内核文件不见了。还好备份有。
> 
> 等下个版本看看，有需要就先用旧版吧

如果repo能回退就好了。

**Comment by tuanqing** [comment]
> > > 还好有两个虚拟机有48+o备份。
> > > 换回48+o无线正常。
> > > 开始以为是lede更新后问题，切老版本编译一次，还是不行。
> > > 换老内核好了
> > > 此仓库不支持版本回退。回退后内核文件不见了。还好备份有。
> > 
> > 
> > 等下个版本看看，有需要就先用旧版吧
> 
> 如果repo能回退就好了。

不能回退，因为每次更新都是先清理后 `force push` 。即使回退到对应 `commit` ，文件也是不在的。
