### ISSUE TITLE
打包失败 求解

### ISSUE THREAD

**Issue by 0x01x0** [tuanqing/mknop#73]
![](https://img.0x01x0.ml/images/2020/12/29/photo_2020-12-29_15-08-16.jpg)

Kernel not configured for semaphores (System V IPC). Not using udev synchronisation code.
Kernel not configured for semaphores (System V IPC). Not using udev synchronisation code.
Kernel not configured for semaphores (System V IPC). Not using udev synchronisation code.
losetup: cannot find an unused loop device
e => error when losetup out/l1pro/20.12.29-150730-l1pro-5.4.83-aarch64-openwrt-firmware.img
lsblk: failed to access sysfs directory: /sys/dev/block: No such file or directory
lsblk: failed to access sysfs directory: /sys/dev/block: No such file or directory
chmod: cannot access './out': No such file or directory

**Comment by tuanqing** [comment]
换个环境，如果使用 `WSL`，请尝试 `WSL2`
