### ISSUE TITLE
请问目前脚本生成的固件该如何写入emmc？

### ISSUE THREAD

**Issue by adamw92** [tuanqing/mknop#8]
编译好固件刷到u盘可以成功启动，但是无法写入emmc…
请问该如何操作？

**Comment by hcym** [comment]
刚刚准备下手，看到不敢动了，这次版本除了没有bbr其它都比xq7的好。大半年前的事基本忘光了，再等等看看吧

**Comment by wenter** [comment]
很好呀，希望大佬更新一下
支持最新内核BBR
当然最重要的是再来一个一键写入emmc
