### ISSUE TITLE
到底用了什么魔法保存/应用加载时间很快？

### ISSUE THREAD

**Issue by HSK077** [tuanqing/mknop#83]
非常好奇！是和源码编译有关，还是主题的关系？
每次保存没在转圈圈/倒计时什么的，一气呵成爽快

**Comment by tuanqing** [comment]
> 非常好奇！是和源码编译有关，还是主题的关系？
> 每次保存没在转圈圈/倒计时什么的，一气呵成爽快

@HSK077 Lienol 的 [luci](https://github.com/Lienol/openwrt-luci)
